export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import { serverDb } from "@/lib/supabase";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  const db = serverDb();
  const tripId = params.id;

  // Fetch trip
  const { data: trip, error: tripError } = await db.from("trips").select("*").eq("id", tripId).single();
  if (tripError) return NextResponse.json({ error: tripError.message }, { status: 404 });

  // Fetch travelers
  const { data: travelers } = await db.from("travelers").select("*").eq("trip_id", tripId);
  const tMap = new Map((travelers ?? []).map((t: any) => [t.id, t]));

  // Fetch expenses
  const { data: expenses } = await db
    .from("expenses")
    .select("*, paid_by:travelers!paid_by_id(*), splits:expense_splits(*)")
    .eq("trip_id", tripId)
    .order("date", { ascending: true });

  // Fetch settlement instructions
  const { data: settlementPayments } = await db
    .from("settlement_payments")
    .select("*, from_traveler:travelers!from_traveler_id(*), to_traveler:travelers!to_traveler_id(*)")
    .eq("trip_id", tripId);

  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();

  // --- Title ---
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text("Trip Summary Report", 14, 18);

  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105);
  doc.text(trip.name, 14, 26);
  if (trip.destination) doc.text(`Destination: ${trip.destination}`, 14, 32);
  if (trip.start_date || trip.end_date) {
    doc.text(`Dates: ${trip.start_date ?? "?"} – ${trip.end_date ?? "?"}`, 14, 38);
  }

  const realTravelers = (travelers ?? []).filter((t: any) => !t.is_pool);

  // --- Expenses Table ---
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("Expenses", 14, 52);

  const expenseRows = (expenses ?? []).map((e: any) => [
    e.date,
    e.category,
    e.paid_by?.name ?? "?",
    e.payment_type,
    `RM ${Number(e.myr_amount).toFixed(2)}`,
    e.foreign_amount ? `${trip.foreign_currency} ${Number(e.foreign_amount).toLocaleString()}` : "",
    e.notes ?? "",
  ]);

  autoTable(doc, {
    startY: 56,
    head: [["Date", "Category", "Paid By", "Payment", "MYR Amount", `${trip.foreign_currency} Amount`, "Notes"]],
    body: expenseRows,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [16, 185, 129], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // --- Per-Person Summary ---
  const perPersonSpent: Record<string, number> = {};
  for (const t of realTravelers) perPersonSpent[t.id] = 0;
  for (const e of expenses ?? []) {
    const splits = e.splits ?? [];
    for (const s of splits) {
      if (perPersonSpent[s.traveler_id] !== undefined) {
        perPersonSpent[s.traveler_id] += Number(s.amount);
      }
    }
  }

  const summaryY = (doc as any).lastAutoTable?.finalY ?? 100;
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("Per-Person Summary", 14, summaryY + 12);

  const totalSpent = (expenses ?? []).reduce((s: number, e: any) => s + Number(e.myr_amount), 0);
  const summaryRows = realTravelers.map((t: any) => {
    const paid = (expenses ?? [])
      .filter((e: any) => e.paid_by_id === t.id)
      .reduce((s: number, e: any) => s + Number(e.myr_amount), 0);
    const owed = perPersonSpent[t.id] ?? 0;
    const net = paid - owed;
    return [t.name, `RM ${paid.toFixed(2)}`, `RM ${owed.toFixed(2)}`, `${net >= 0 ? "+" : ""}RM ${net.toFixed(2)}`];
  });

  autoTable(doc, {
    startY: summaryY + 16,
    head: [["Traveler", "Paid", "Owes", "Net Balance"]],
    body: summaryRows,
    foot: [["Total", `RM ${totalSpent.toFixed(2)}`, "", ""]],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [16, 185, 129], textColor: 255 },
    footStyles: { fillColor: [241, 245, 249], fontStyle: "bold" },
  });

  // --- Settlement Instructions ---
  if (settlementPayments && settlementPayments.length > 0) {
    const settlementY = (doc as any).lastAutoTable?.finalY ?? 160;
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text("Settlement History", 14, settlementY + 12);

    const settlementRows = settlementPayments.map((p: any) => [
      new Date(p.created_at).toLocaleDateString("en-MY"),
      p.from_traveler?.name ?? "?",
      p.to_traveler?.name ?? "?",
      `RM ${Number(p.amount).toFixed(2)}`,
    ]);

    autoTable(doc, {
      startY: settlementY + 16,
      head: [["Date", "From", "To", "Amount"]],
      body: settlementRows,
      styles: { fontSize: 9 },
      headStyles: { fillColor: [217, 119, 6], textColor: 255 },
    });
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by TravelSTA on ${new Date().toLocaleDateString("en-MY")}`,
    14,
    doc.internal.pageSize.getHeight() - 8
  );

  const buffer = Buffer.from(doc.output("arraybuffer"));
  const safeName = trip.name.replace(/[^a-z0-9]/gi, "-").toLowerCase();

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${safeName}-summary.pdf"`,
    },
  });
}
